# Conclusion

## Madeline Witzeman

In [2]:
import pandas

In [3]:
data_models = [['N/A', 'N/A', 'N/A', 'N/A', '2.44', '2.62'], ['LSTM', 'Unstacked', 'No', '16', '2.38', '2.56'], ['LSTM', 'Unstacked', 'Yes', '32', '2.36', '2.56'], ['LSTM', 'Stacked', 'Yes', '32', '2.45', '2.58'], ['LSTM', 'Stacked', 'Yes', '64', '2.45', '2.60'], ['GRU', 'Stacked', 'Yes', '32', '2.31', '2.44'], ['1d Convnet + LSTM', 'Stacked', 'No', '16', '2.43', '2.63']]

In [4]:
df = pandas.DataFrame(data_models, index=[1,2,3,4,5,6,7], columns=['Type of RNN', 'Stacked/Unstacked', 'Dropout Used?', 'Units per Layer', 'Val MAE (Deg C)', 'Test MAE (Deg C)'])
print(df)

         Type of RNN Stacked/Unstacked Dropout Used? Units per Layer  \
1                N/A               N/A           N/A             N/A   
2               LSTM         Unstacked            No              16   
3               LSTM         Unstacked           Yes              32   
4               LSTM           Stacked           Yes              32   
5               LSTM           Stacked           Yes              64   
6                GRU           Stacked           Yes              32   
7  1d Convnet + LSTM           Stacked            No              16   

  Val MAE (Deg C) Test MAE (Deg C)  
1            2.44             2.62  
2            2.38             2.56  
3            2.36             2.56  
4            2.45             2.58  
5            2.45             2.60  
6            2.31             2.44  
7            2.43             2.63  


In conclusion, when comparing against the "common sense model" baseline assumption, Model #6 (Dropout-Regularized Stacked GRU, 32 units per layer) performed the best with a validation MAE of 2.31 deg C and a test MAE of 2.44 deg C.

Utilizing dropout didn't appear to significantly improve model performance. Additionally, using a stacked approach and increasing the number of units per layer decreased model performance with LSTM. Switching to GRU when using the dropout-regularized stacked approach notably improved model performance. Lastly, using 1d convnets with a RNN (LSTM) approach hurt model performance.

Overall, it appears to be difficult to significantly outperform the common sense model when predicting weather.

In [1]:
!pip install nbconvert

In [ ]:
!jupyter nbconvert --to html "/content/drive/MyDrive/Colab Notebooks/BA 64061 Assignment 2 Summary Report Madeline Witzeman.ipynb"

[NbConvertApp] Converting notebook /content/drive/MyDrive/Colab Notebooks/BA 64061 Assignment 2 Summary Report Madeline Witzeman.ipynb to html
[NbConvertApp] Writing 606371 bytes to /content/drive/MyDrive/Colab Notebooks/BA 64061 Assignment 2 Summary Report Madeline Witzeman.html


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
